/*==============================================================*/
/*                       原有库表字段修改                                           */
/*==============================================================*/

--大票表
ALTER TABLE  CD_EDRAFT ADD (ZY_FLAG VARCHAR2(2)  DEFAULT '00' );
COMMENT ON COLUMN CD_EDRAFT.ZY_FLAG IS '自动入池标识（00 非自动入池  01 自动入池）';
COMMENT ON COLUMN CD_EDRAFT.ZY_FLAG IS '自动入池标识（00 非自动入池  01 自动入池）';
ALTER TABLE CD_EDRAFT ADD CREDIT_OBJ_TYPE VARCHAR2(10);
COMMENT ON COLUMN CD_EDRAFT.CREDIT_OBJ_TYPE  IS '额度主体类型  1-同业额度  2-对公额度';
ALTER TABLE CD_EDRAFT ADD GUARANT_DISC_NAME VARCHAR2(30);
COMMENT ON COLUMN CD_EDRAFT.GUARANT_DISC_NAME  IS '保贴人名称';
ALTER TABLE CD_EDRAFT ADD GUARANT_DISC_NO VARCHAR2(30);
COMMENT ON COLUMN CD_EDRAFT.GUARANT_DISC_NO  IS '保贴编号';
ALTER TABLE CD_EDRAFT ADD ACPT_HEAD_BANK_NO VARCHAR2(12);
COMMENT ON COLUMN CD_EDRAFT.ACPT_HEAD_BANK_NO  IS '承兑行总行行号';
ALTER TABLE CD_EDRAFT ADD ACPT_HEAD_BANK_NAME VARCHAR2(150);
COMMENT ON COLUMN CD_EDRAFT.ACPT_HEAD_BANK_NAME  IS '承兑行总行行名';
ALTER TABLE CD_EDRAFT ADD cp_Flag VARCHAR2(1) DEFAULT '0';
COMMENT ON COLUMN CD_EDRAFT.cp_Flag  IS '财票标识';

--池票据表
ALTER TABLE  PL_POOL ADD LAST_RISK_LEVEL VARCHAR2(5) ;
COMMENT ON COLUMN PL_POOL.LAST_RISK_LEVEL IS '最近一次的风险类型';
ALTER TABLE  PL_POOL ADD DELAY_DAYS INT  default 0 not null;
COMMENT ON COLUMN PL_POOL.DELAY_DAYS IS '顺延日';
ALTER TABLE PL_POOL ADD cp_Flag VARCHAR2(1) DEFAULT '0';
COMMENT ON COLUMN PL_POOL.cp_Flag  IS '财票标识';
ALTER TABLE PL_POOL ADD ACPT_HEAD_BANK_NO VARCHAR2(12);
COMMENT ON COLUMN PL_POOL.ACPT_HEAD_BANK_NO  IS '承兑行总行行号';
ALTER TABLE PL_POOL ADD ACPT_HEAD_BANK_NAME VARCHAR2(150);
COMMENT ON COLUMN PL_POOL.ACPT_HEAD_BANK_NAME  IS '承兑行总行行名';
ALTER TABLE  PL_POOL ADD (AUDIT_STATUS VARCHAR2(10) );
COMMENT ON COLUMN PL_POOL.AUDIT_STATUS IS '审批状态表';
ALTER TABLE  PL_POOL ADD (crt_Tm DATE );
COMMENT ON COLUMN PL_POOL.crt_Tm IS '创建时间';
ALTER TABLE PL_POOL ADD CREDIT_OBJ_TYPE VARCHAR2(30);
COMMENT ON COLUMN PL_POOL.CREDIT_OBJ_TYPE  IS '额度主体类型  1-同业额度  2-对公额度';
ALTER TABLE PL_POOL ADD GUARANT_DISC_NAME VARCHAR2(30);
COMMENT ON COLUMN PL_POOL.GUARANT_DISC_NAME  IS '保贴人名称';
ALTER TABLE PL_POOL ADD GUARANT_DISC_NO VARCHAR2(30);
COMMENT ON COLUMN PL_POOL.GUARANT_DISC_NO  IS '保贴编号';

--入池表
ALTER TABLE PL_POOL_IN ADD CREDIT_OBJ_TYPE VARCHAR2(30);
COMMENT ON COLUMN PL_POOL_IN.CREDIT_OBJ_TYPE  IS '额度主体类型  1-同业额度  2-对公额度';
ALTER TABLE PL_POOL_IN ADD GUARANT_DISC_NAME VARCHAR2(30);
COMMENT ON COLUMN PL_POOL_IN.GUARANT_DISC_NAME  IS '保贴人名称';
ALTER TABLE PL_POOL_IN ADD GUARANT_DISC_NO VARCHAR2(30);
COMMENT ON COLUMN PL_POOL_IN.GUARANT_DISC_NO  IS '保贴编号';
ALTER TABLE PL_POOL_IN ADD ACPT_HEAD_BANK_NO VARCHAR2(12);
COMMENT ON COLUMN PL_POOL_IN.ACPT_HEAD_BANK_NO  IS '承兑行总行行号';
ALTER TABLE PL_POOL_IN ADD ACPT_HEAD_BANK_NAME VARCHAR2(150);
COMMENT ON COLUMN PL_POOL_IN.ACPT_HEAD_BANK_NAME  IS '承兑行总行行名';
ALTER TABLE PL_POOL_IN ADD task_Date TIMESTAMP ;
COMMENT ON COLUMN PL_POOL_IN.task_Date IS '操作时间';

--出池表
ALTER TABLE PL_POOL_OUT ADD FORBID_FLAG VARCHAR2(10) DEFAULT '0';
COMMENT ON COLUMN PL_POOL_OUT.FORBID_FLAG  IS '禁止背书标识';
ALTER TABLE PL_POOL_OUT ADD task_Date TIMESTAMP ;
COMMENT ON COLUMN PL_POOL_OUT.task_Date IS '操作时间';

--虚拟票据表
ALTER TABLE pl_vtrust ADD CREDIT_OBJ_TYPE VARCHAR2(10);
COMMENT ON COLUMN pl_vtrust.CREDIT_OBJ_TYPE  IS '额度主体类型  1-同业额度  2-对公额度';
ALTER TABLE pl_vtrust ADD GUARANT_DISC_NAME VARCHAR2(30);
COMMENT ON COLUMN pl_vtrust.GUARANT_DISC_NAME  IS '保贴人名称';
ALTER TABLE pl_vtrust ADD GUARANT_DISC_NO VARCHAR2(30);
COMMENT ON COLUMN pl_vtrust.GUARANT_DISC_NO  IS '保贴编号';
ALTER TABLE pl_vtrust ADD ACPT_HEAD_BANK_NO VARCHAR2(12);
COMMENT ON COLUMN pl_vtrust.ACPT_HEAD_BANK_NO  IS '承兑行总行行号';
ALTER TABLE pl_vtrust ADD ACPT_HEAD_BANK_NAME VARCHAR2(150);
COMMENT ON COLUMN pl_vtrust.ACPT_HEAD_BANK_NAME  IS '承兑行总行行名';

--贴现表
ALTER TABLE PL_DISCOUNT ADD task_Date TIMESTAMP ;
COMMENT ON COLUMN PL_DISCOUNT.task_Date IS '操作时间';

--保贴表
ALTER TABLE PED_GUARANTEE_CREDIT ADD CREDIT_OBJ_TYPE VARCHAR2(10);
COMMENT ON COLUMN PED_GUARANTEE_CREDIT.CREDIT_OBJ_TYPE  IS '额度主体类型  1-同业额度  2-对公额度';
ALTER TABLE PED_GUARANTEE_CREDIT ADD GUARANT_DISC_NAME VARCHAR2(30);
COMMENT ON COLUMN PED_GUARANTEE_CREDIT.GUARANT_DISC_NAME  IS '保贴人名称';
ALTER TABLE PED_GUARANTEE_CREDIT ADD GUARANT_DISC_NO VARCHAR2(30);
COMMENT ON COLUMN PED_GUARANTEE_CREDIT.GUARANT_DISC_NO  IS '保贴编号';

--资产池表
ALTER TABLE PED_ASSET_POOL ADD (DEAL_STATUS VARCHAR2(6) DEFAULT 'DS_002' NOT NULL);
COMMENT ON COLUMN PED_ASSET_POOL.DEAL_STATUS IS '处理标识  DS_001-处理中  DS_002-未处理';

--主业务合同表
alter table PED_CRDT_PRDCT add (IS_ONLINE varchar2(10) default '0');
COMMENT ON COLUMN PED_CRDT_PRDCT.IS_ONLINE IS '是否线上业务   0-否  1-是';
alter table PED_CRDT_PRDCT add (MIN_DUE_DATE DATE );
COMMENT ON COLUMN PED_CRDT_PRDCT.MIN_DUE_DATE IS '借据最早到期日';


--借据表
alter table PED_CREDIT_DETAIL add (IF_ADVANCE_AMT varchar2(10) default '0'); 
alter table PED_CREDIT_DETAIL add (LOAN_ADVANCE_NO varchar2(50) default NULL); 
COMMENT ON COLUMN PED_CREDIT_DETAIL.IF_ADVANCE_AMT IS '是否垫款 0： 否 1: 是';
COMMENT ON COLUMN PED_CREDIT_DETAIL.LOAN_ADVANCE_NO IS '垫款借据号';
ALTER TABLE PED_CREDIT_DETAIL ADD INITIAL_MARGIN_AMT NUMBER(20,2)  DEFAULT 0 ;
COMMENT ON COLUMN PED_CREDIT_DETAIL.INITIAL_MARGIN_AMT IS '业务保证金初始金额';
ALTER TABLE PED_CREDIT_DETAIL ADD IS_ONLINE VARCHAR2(10) default '0';
COMMENT ON COLUMN PED_CREDIT_DETAIL.IS_ONLINE IS '线上线下标记';
ALTER TABLE PED_CREDIT_DETAIL ADD task_Date TIMESTAMP ;
COMMENT ON COLUMN PED_CREDIT_DETAIL.task_Date IS '操作时间';

--MIS出账信息同步表
alter table MIS_CREDIT add (OLD_LOAN_NO varchar2(50) default NULL); 
COMMENT ON COLUMN MIS_CREDIT.OLD_LOAN_NO IS '原借据编号';

--票据池协议表 
alter table PED_PROTOCOL add IS_ACCT_CHECK varchar(2) default '1';
COMMENT ON COLUMN PED_PROTOCOL.IS_ACCT_CHECK IS '票据池保证金支取是否人工审核   0-否  1-是';

--银行黑灰名单表
ALTER TABLE PED_BLACKLIST ADD REMARK VARCHAR2(500);
COMMENT ON COLUMN PED_BLACKLIST.REMARK  IS '备注';

--日志表
alter table TRANS_LOG modify M_REMARK VARCHAR2(1500);
alter table TRANS_LOG ADD M_RSPMSGCONTENT blob;
ALTER TABLE T_LOG MODIFY (L_OPERCONTENT VARCHAR2(3000));
ALTER TABLE T_LOG ADD (L_MEMBER_CODE VARCHAR2(6));
comment on column T_LOG.L_MEMBER_CODE is '会员编码';
ALTER TABLE T_LOG ADD (L_USERID VARCHAR2(40));
comment on column T_LOG.L_USERID is '用户ID';
ALTER TABLE T_LOG ADD (L_OPER_TYPE VARCHAR2(1) DEFAULT '4');
comment on column T_LOG.L_OPER_TYPE is '操作类型';
ALTER TABLE T_LOG ADD (L_SERVER_IP VARCHAR2(15));
comment on column T_LOG.L_SERVER_IP is '服务端IP';
ALTER TABLE T_LOG ADD (L_DESC VARCHAR2(150));
comment on column T_LOG.L_DESC is '功能描述';

--角色表
ALTER TABLE  T_ROLE ADD R_MEMBER_CODE VARCHAR2(10)  default '0' ;
COMMENT ON COLUMN T_ROLE.R_MEMBER_CODE IS '票交所会员号';

--机构表
ALTER TABLE t_department ADD (YC_FLAG VARCHAR2(1) DEFAULT '0' );
COMMENT ON COLUMN t_department.YC_FLAG  IS '在线银承开关';
ALTER TABLE t_department ADD (LD_FLAG VARCHAR2(1) DEFAULT '0' );
COMMENT ON COLUMN t_department.LD_FLAG  IS '在线流贷开关';

--删除未使用表
DROP TABLE PL_HKB_BANK ;
DROP TABLE PL_STOCK; --票据资产库存明细实体
DROP TABLE PL_STOCK_IN; --票据资产库存入库明细实体
DROP TABLE PL_STOCK_IN_BATCH; --票据资产库存入库批次实体
DROP TABLE PL_STOCK_OUT; --票据资产库存出库明细实体
DROP TABLE PL_STOCK_OUT_BATCH; --票据资产库存出库批次实体

--字段扩容
--在线银承收票人
alter table PED_ONLINE_ACPT_INFO modify PAYEE_ACCT_NO VARCHAR2(40);
--在线流贷收款人
alter table PED_ONLINE_CRDT_INFO modify PAYEE_ACCT_NO VARCHAR2(40);
--在线银承协议历史表	扣收保证金账号
alter table PED_ONLINE_ACPT_PROTOCOL_HIST modify DEPOSIT_ACCT_NO VARCHAR2(40);
--在线流贷协议历史表	放款账户账号	扣款账户账号
alter table PED_ONLINE_CRDT_PROTOCOL_HIST modify LOAN_ACCT_NO VARCHAR2(40);
alter table PED_ONLINE_CRDT_PROTOCOL_HIST modify DEDU_ACCT_NO VARCHAR2(40);
----在线流贷支付计划表	付款账号 付款户名  收款人账号  收款人名称
alter table PL_CRDT_PAY_PLAN modify (LOAN_ACCT_NO VARCHAR2(40),DEDU_ACCT_NO VARCHAR2(40),LOAN_ACCT_NAME VARCHAR2(240),DEDU_ACCT_NAME VARCHAR2(240));
--在线流贷支付计划缓存表	付款账号 付款户名  收款人账号  收款人名称
alter table PL_CRDT_PAY_CACHE_PLAN modify (LOAN_ACCT_NO VARCHAR2(40),DEDU_ACCT_NO VARCHAR2(40),LOAN_ACCT_NAME VARCHAR2(240),DEDU_ACCT_NAME VARCHAR2(240));
--在线流贷支付计划历史表	付款账号 付款户名  收款人账号  收款人名称
alter table PL_CRDT_PAY_PLAN_HIST modify (LOAN_ACCT_NO VARCHAR2(40),DEDU_ACCT_NO VARCHAR2(40),LOAN_ACCT_NAME VARCHAR2(240),DEDU_ACCT_NAME VARCHAR2(240));
--在线银承批次表
alter table PL_ONLINE_ACPT_BATCH modify (APPLY_ACCT VARCHAR2(40),DEPOSIT_ACCT_NO VARCHAR2(40),DEPOSIT_ACCT_NAME VARCHAR2(240),APPLY_NAME VARCHAR2(240));
--在银承明细表
alter table PL_ONLINE_ACPT_DETAIL modify (ISSUER_ACCT VARCHAR2(40),PAYEE_ACCT VARCHAR2(40),ISSUER_NAME VARCHAR2(240),PAYEE_NAME VARCHAR2(240),TRANS_ACCOUNT VARCHAR2(40));
--在线银承批次缓存表
alter table PL_ONLINE_ACPT_CACHE_BATCH modify (APPLY_ACCT VARCHAR2(40),DEPOSIT_ACCT_NO VARCHAR2(40),DEPOSIT_ACCT_NAME VARCHAR2(240),APPLY_NAME VARCHAR2(240));
--在银承明细缓存表
alter table PL_ONLINE_ACPT_CACHE_DETAIL modify (ISSUER_ACCT VARCHAR2(40),PAYEE_ACCT VARCHAR2(40),ISSUER_NAME VARCHAR2(240),PAYEE_NAME VARCHAR2(240));
--在线流贷业务表
alter table PL_ONLINE_CRDT modify (DEDU_ACCT_NO VARCHAR2(40),CREDIT_ACCT VARCHAR2(40),DEPOSIT_ACCT_NO VARCHAR2(40),TRANS_ACCOUNT VARCHAR2(40));
--在线流贷业务缓存表
alter table PL_ONLINE_CACHE_CRDT modify (DEDU_ACCT_NO VARCHAR2(40),CREDIT_ACCT VARCHAR2(40),DEPOSIT_ACCT_NO VARCHAR2(40),TRANS_ACCOUNT VARCHAR2(40));
alter table PED_ONLINE_ACPT_INFO_HIST modify (PAYEE_ACCT_NO VARCHAR2(40));
--在线流贷收款人历史表
alter table PED_ONLINE_CRDT_INFO_HIST modify (PAYEE_ACCT_NO VARCHAR2(40));


--在线银承表
alter table PED_ONLINE_ACPT_PROTOCOL add (DEPOSIT_RATE_FLOAT_VALUE_temp number(20,6));
update PED_ONLINE_ACPT_PROTOCOL set DEPOSIT_RATE_FLOAT_VALUE_temp = round(DEPOSIT_RATE_FLOAT_VALUE,2);
alter table PED_ONLINE_ACPT_PROTOCOL drop column DEPOSIT_RATE_FLOAT_VALUE;
alter table PED_ONLINE_ACPT_PROTOCOL add (DEPOSIT_RATE_FLOAT_VALUE number(20,6));
update PED_ONLINE_ACPT_PROTOCOL set DEPOSIT_RATE_FLOAT_VALUE = DEPOSIT_RATE_FLOAT_VALUE_temp;
alter table PED_ONLINE_ACPT_PROTOCOL drop column DEPOSIT_RATE_FLOAT_VALUE_temp;
--在线流贷表
alter table PED_ONLINE_CRDT_PROTOCOL add (RATE_FLOAT_VALUE_temp number(20,6),OVER_RATE_FLOAT_VALUE_temp NUMBER(20,6));
update PED_ONLINE_CRDT_PROTOCOL set RATE_FLOAT_VALUE_temp = round(RATE_FLOAT_VALUE,2);
alter table PED_ONLINE_CRDT_PROTOCOL drop column RATE_FLOAT_VALUE;
alter table PED_ONLINE_CRDT_PROTOCOL add (RATE_FLOAT_VALUE number(20,6));
update PED_ONLINE_CRDT_PROTOCOL set RATE_FLOAT_VALUE = RATE_FLOAT_VALUE_temp;
alter table PED_ONLINE_CRDT_PROTOCOL drop column RATE_FLOAT_VALUE_temp;
update PED_ONLINE_CRDT_PROTOCOL set OVER_RATE_FLOAT_VALUE_temp = round(OVER_RATE_FLOAT_VALUE,2);
alter table PED_ONLINE_CRDT_PROTOCOL drop column OVER_RATE_FLOAT_VALUE;
alter table PED_ONLINE_CRDT_PROTOCOL add (OVER_RATE_FLOAT_VALUE number(20,6));
update PED_ONLINE_CRDT_PROTOCOL set OVER_RATE_FLOAT_VALUE = OVER_RATE_FLOAT_VALUE_temp;
alter table PED_ONLINE_CRDT_PROTOCOL drop column OVER_RATE_FLOAT_VALUE_temp;
--在线银承历史表
alter table PED_ONLINE_ACPT_PROTOCOL_HIST add (DEPOSIT_RATE_FLOAT_VALUE_temp number(20,6));
update PED_ONLINE_ACPT_PROTOCOL_HIST set DEPOSIT_RATE_FLOAT_VALUE_temp = round(DEPOSIT_RATE_FLOAT_VALUE,2);
alter table PED_ONLINE_ACPT_PROTOCOL_HIST drop column DEPOSIT_RATE_FLOAT_VALUE;
alter table PED_ONLINE_ACPT_PROTOCOL_HIST add (DEPOSIT_RATE_FLOAT_VALUE number(20,6));
update PED_ONLINE_ACPT_PROTOCOL_HIST set DEPOSIT_RATE_FLOAT_VALUE = DEPOSIT_RATE_FLOAT_VALUE_temp;
alter table PED_ONLINE_ACPT_PROTOCOL_HIST drop column DEPOSIT_RATE_FLOAT_VALUE_temp;
--在线流贷历史表
alter table PED_ONLINE_CRDT_PROTOCOL_HIST add (RATE_FLOAT_VALUE_temp number(20,6),OVER_RATE_FLOAT_VALUE_temp NUMBER(20,6));
update PED_ONLINE_CRDT_PROTOCOL_HIST set RATE_FLOAT_VALUE_temp = round(RATE_FLOAT_VALUE,2);
alter table PED_ONLINE_CRDT_PROTOCOL_HIST drop column RATE_FLOAT_VALUE;
alter table PED_ONLINE_CRDT_PROTOCOL_HIST add (RATE_FLOAT_VALUE number(20,6));
update PED_ONLINE_CRDT_PROTOCOL_HIST set RATE_FLOAT_VALUE = RATE_FLOAT_VALUE_temp;
alter table PED_ONLINE_CRDT_PROTOCOL_HIST drop column RATE_FLOAT_VALUE_temp;
update PED_ONLINE_CRDT_PROTOCOL_HIST set OVER_RATE_FLOAT_VALUE_temp = round(OVER_RATE_FLOAT_VALUE,2);
alter table PED_ONLINE_CRDT_PROTOCOL_HIST drop column OVER_RATE_FLOAT_VALUE;
alter table PED_ONLINE_CRDT_PROTOCOL_HIST add (OVER_RATE_FLOAT_VALUE number(20,6));
update PED_ONLINE_CRDT_PROTOCOL_HIST set OVER_RATE_FLOAT_VALUE = OVER_RATE_FLOAT_VALUE_temp;
alter table PED_ONLINE_CRDT_PROTOCOL_HIST drop column OVER_RATE_FLOAT_VALUE_temp;


--在线银承批次表
alter table PL_ONLINE_ACPT_BATCH add (DEPOSIT_RATE_FLOAT_VALUE_temp number(20,6));
update PL_ONLINE_ACPT_BATCH set DEPOSIT_RATE_FLOAT_VALUE_temp = round(DEPOSIT_RATE_FLOAT_VALUE,2);
alter table PL_ONLINE_ACPT_BATCH drop column DEPOSIT_RATE_FLOAT_VALUE;
alter table PL_ONLINE_ACPT_BATCH add (DEPOSIT_RATE_FLOAT_VALUE number(20,6));
update PL_ONLINE_ACPT_BATCH set DEPOSIT_RATE_FLOAT_VALUE = DEPOSIT_RATE_FLOAT_VALUE_temp;
alter table PL_ONLINE_ACPT_BATCH drop column DEPOSIT_RATE_FLOAT_VALUE_temp;
--在线流贷批次表
alter table PL_ONLINE_CRDT add (RATE_FLOAT_VALUE_temp number(20,6),OVER_RATE_FLOAT_VALUE_temp NUMBER(20,6));
update PL_ONLINE_CRDT set RATE_FLOAT_VALUE_temp = round(RATE_FLOAT_VALUE,2);
alter table PL_ONLINE_CRDT drop column RATE_FLOAT_VALUE;
alter table PL_ONLINE_CRDT add (RATE_FLOAT_VALUE number(20,6));
update PL_ONLINE_CRDT set RATE_FLOAT_VALUE = RATE_FLOAT_VALUE_temp;
alter table PL_ONLINE_CRDT drop column RATE_FLOAT_VALUE_temp;
update PL_ONLINE_CRDT set OVER_RATE_FLOAT_VALUE_temp = round(OVER_RATE_FLOAT_VALUE,2);
alter table PL_ONLINE_CRDT drop column OVER_RATE_FLOAT_VALUE;
alter table PL_ONLINE_CRDT add (OVER_RATE_FLOAT_VALUE number(20,6));
update PL_ONLINE_CRDT set OVER_RATE_FLOAT_VALUE = OVER_RATE_FLOAT_VALUE_temp;
alter table PL_ONLINE_CRDT drop column OVER_RATE_FLOAT_VALUE_temp;

-------------------------------------------------------融合改造新增字段--------------------------------------------------------------------------------
--大票表
ALTER TABLE CD_EDRAFT ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN CD_EDRAFT.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE CD_EDRAFT ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN CD_EDRAFT.END_RANGE_NO  IS '票据结束子区间号';

ALTER TABLE CD_EDRAFT ADD STANDARD_AMT NUMBER(20,2)  DEFAULT 0.01;
COMMENT ON COLUMN CD_EDRAFT.STANDARD_AMT  IS '标准金额';

ALTER TABLE CD_EDRAFT ADD TRADE_AMT NUMBER(20,2)  DEFAULT 0;
COMMENT ON COLUMN CD_EDRAFT.TRADE_AMT  IS '交易金额(等分化票据实际交易金额)';

ALTER TABLE CD_EDRAFT ADD DRAFT_SOURCE VARCHAR2(6)  DEFAULT 'CS01';
COMMENT ON COLUMN CD_EDRAFT.DRAFT_SOURCE  IS '票据来源';

ALTER TABLE CD_EDRAFT ADD SPLIT_FLAG VARCHAR2(1)   DEFAULT '0';
COMMENT ON COLUMN CD_EDRAFT.SPLIT_FLAG  IS '是否允许拆分标记 1是 0否';

ALTER TABLE CD_EDRAFT ADD HILR_ID VARCHAR2(40);
COMMENT ON COLUMN CD_EDRAFT.HILR_ID  IS '持有id';

ALTER TABLE CD_EDRAFT ADD SPLIT_ID VARCHAR2(40);
COMMENT ON COLUMN CD_EDRAFT.SPLIT_ID  IS '拆分前的大票主键id';

ALTER TABLE CD_EDRAFT ADD ed_AcctNAME VARCHAR2(300);
COMMENT ON COLUMN CD_EDRAFT.ed_AcctNAME  IS '出票人账号名称';

ALTER TABLE CD_EDRAFT ADD ed_pyeeAcctNAME VARCHAR2(300);
COMMENT ON COLUMN CD_EDRAFT.ed_pyeeAcctNAME  IS '收款人账号名称';

ALTER TABLE CD_EDRAFT ADD ed_accptrAcctNAME VARCHAR2(300);
COMMENT ON COLUMN CD_EDRAFT.ed_accptrAcctNAME  IS '承兑人账号名称';

ALTER TABLE CD_EDRAFT ADD TRAN_RPIOR_NAME VARCHAR2(300);
COMMENT ON COLUMN CD_EDRAFT.TRAN_RPIOR_NAME  IS '直接前手名称';



--池票据表

ALTER TABLE PL_POOL ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PL_POOL.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE PL_POOL ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PL_POOL.END_RANGE_NO  IS '票据结束子区间号';

ALTER TABLE PL_POOL ADD STANDARD_AMT NUMBER(20,2)  DEFAULT 0.01;
COMMENT ON COLUMN PL_POOL.STANDARD_AMT  IS '标准金额';

ALTER TABLE PL_POOL ADD TRADE_AMT NUMBER(20,2)  DEFAULT 0;
COMMENT ON COLUMN PL_POOL.TRADE_AMT  IS '交易金额(等分化票据实际交易金额)';

ALTER TABLE PL_POOL ADD DRAFT_SOURCE VARCHAR2(6)  DEFAULT 'CS01';
COMMENT ON COLUMN PL_POOL.DRAFT_SOURCE  IS '票据来源';

ALTER TABLE PL_POOL ADD SPLIT_FLAG VARCHAR2(1) DEFAULT '0';
COMMENT ON COLUMN PL_POOL.SPLIT_FLAG  IS '是否允许拆分标记 1是 0否';

ALTER TABLE PL_POOL ADD HILR_ID VARCHAR2(40);
COMMENT ON COLUMN PL_POOL.HILR_ID  IS '持有id';

ALTER TABLE PL_POOL ADD SPLIT_ID VARCHAR2(40);
COMMENT ON COLUMN PL_POOL.SPLIT_ID  IS '拆分前的大票主键id';

ALTER TABLE PL_POOL ADD TRANS_ID VARCHAR2(40);
COMMENT ON COLUMN PL_POOL_IN.TRANS_ID  IS '交易ID';

ALTER TABLE PL_POOL ADD pl_drwrAcctName VARCHAR2(300);
COMMENT ON COLUMN PL_POOL.pl_drwrAcctName  IS '出票人账户名称';

ALTER TABLE PL_POOL ADD pl_pyeeAcctName VARCHAR2(300);
COMMENT ON COLUMN PL_POOL.pl_pyeeAcctName  IS '收票人账户名称';

ALTER TABLE PL_POOL ADD pl_accptrAcctName VARCHAR2(300);
COMMENT ON COLUMN PL_POOL.pl_accptrAcctName  IS '承兑人账户名称';

--入池表

ALTER TABLE PL_POOL_IN ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PL_POOL_IN.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE PL_POOL_IN ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PL_POOL_IN.END_RANGE_NO  IS '票据结束子区间号';

ALTER TABLE PL_POOL_IN ADD STANDARD_AMT NUMBER(20,2)  DEFAULT 0.01;
COMMENT ON COLUMN PL_POOL_IN.STANDARD_AMT  IS '标准金额';

ALTER TABLE PL_POOL_IN ADD TRADE_AMT NUMBER(20,2)  DEFAULT 0;
COMMENT ON COLUMN PL_POOL_IN.TRADE_AMT  IS '交易金额(等分化票据实际交易金额)';

ALTER TABLE PL_POOL_IN ADD DRAFT_SOURCE VARCHAR2(6)  DEFAULT 'CS01';
COMMENT ON COLUMN PL_POOL_IN.DRAFT_SOURCE  IS '票据来源';

ALTER TABLE PL_POOL_IN ADD SPLIT_FLAG VARCHAR2(1)  DEFAULT '0';
COMMENT ON COLUMN PL_POOL_IN.SPLIT_FLAG  IS '是否允许拆分标记 1是 0否';

ALTER TABLE PL_POOL_IN ADD HILR_ID VARCHAR2(40);
COMMENT ON COLUMN PL_POOL_IN.HILR_ID  IS '持有id';

ALTER TABLE PL_POOL_IN ADD SPLIT_ID VARCHAR2(40);
COMMENT ON COLUMN PL_POOL_IN.SPLIT_ID  IS '拆分前的大票主键id';

ALTER TABLE PL_POOL_IN ADD TRANS_ID VARCHAR2(40);
COMMENT ON COLUMN PL_POOL_IN.TRANS_ID  IS '交易ID';

ALTER TABLE PL_POOL_IN ADD pl_drwrAcctName VARCHAR2(300);
COMMENT ON COLUMN PL_POOL_IN.pl_drwrAcctName  IS '出票人账户名称';

ALTER TABLE PL_POOL_IN ADD pl_pyeeAcctName VARCHAR2(300);
COMMENT ON COLUMN PL_POOL_IN.pl_pyeeAcctName  IS '收票人账户名称';

ALTER TABLE PL_POOL_IN ADD pl_accptrAcctName VARCHAR2(300);
COMMENT ON COLUMN PL_POOL_IN.pl_accptrAcctName  IS '承兑人账户名称';

--出池表

ALTER TABLE PL_POOL_OUT ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PL_POOL_OUT.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE PL_POOL_OUT ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PL_POOL_OUT.END_RANGE_NO  IS '票据结束子区间号';

ALTER TABLE PL_POOL_OUT ADD STANDARD_AMT NUMBER(20,2)  DEFAULT 0.01;
COMMENT ON COLUMN PL_POOL_OUT.STANDARD_AMT  IS '标准金额';

ALTER TABLE PL_POOL_OUT ADD TRADE_AMT NUMBER(20,2)  DEFAULT 0;
COMMENT ON COLUMN PL_POOL_OUT.TRADE_AMT  IS '交易金额(等分化票据实际交易金额)';

ALTER TABLE PL_POOL_OUT ADD DRAFT_SOURCE VARCHAR2(6)  DEFAULT 'CS01';
COMMENT ON COLUMN PL_POOL_OUT.DRAFT_SOURCE  IS '票据来源';

ALTER TABLE PL_POOL_OUT ADD SPLIT_FLAG VARCHAR2(1)  DEFAULT '0';
COMMENT ON COLUMN PL_POOL_OUT.SPLIT_FLAG  IS '是否允许拆分标记 1是 0否';

ALTER TABLE PL_POOL_OUT ADD HILR_ID VARCHAR2(40);
COMMENT ON COLUMN PL_POOL_OUT.HILR_ID  IS '持有id';

ALTER TABLE PL_POOL_OUT ADD SPLIT_ID VARCHAR2(40);
COMMENT ON COLUMN PL_POOL_OUT.SPLIT_ID  IS '拆分前的大票主键id';

ALTER TABLE PL_POOL_OUT ADD TRANS_ID VARCHAR2(40);
COMMENT ON COLUMN PL_POOL_OUT.TRANS_ID  IS '交易ID';

ALTER TABLE PL_POOL_OUT ADD pl_drwrAcctName VARCHAR2(300);
COMMENT ON COLUMN PL_POOL_OUT.pl_drwrAcctName  IS '出票人账户名称';

ALTER TABLE PL_POOL_OUT ADD pl_pyeeAcctName VARCHAR2(300);
COMMENT ON COLUMN PL_POOL_OUT.pl_pyeeAcctName  IS '收票人账户名称';

ALTER TABLE PL_POOL_OUT ADD pl_accptrAcctName VARCHAR2(300);
COMMENT ON COLUMN PL_POOL_OUT.pl_accptrAcctName  IS '承兑人账户名称';

--虚拟票据表

ALTER TABLE pl_vtrust ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN pl_vtrust.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE pl_vtrust ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN pl_vtrust.END_RANGE_NO  IS '票据结束子区间号';

ALTER TABLE pl_vtrust ADD STANDARD_AMT NUMBER(20,2)  DEFAULT 0.01;
COMMENT ON COLUMN pl_vtrust.STANDARD_AMT  IS '标准金额';

ALTER TABLE pl_vtrust ADD TRADE_AMT NUMBER(20,2)  DEFAULT 0;
COMMENT ON COLUMN pl_vtrust.TRADE_AMT  IS '交易金额(等分化票据实际交易金额)';

ALTER TABLE pl_vtrust ADD DRAFT_SOURCE VARCHAR2(6)  DEFAULT 'CS01';
COMMENT ON COLUMN pl_vtrust.DRAFT_SOURCE  IS '票据来源';

ALTER TABLE pl_vtrust ADD SPLIT_FLAG VARCHAR2(1)  DEFAULT '0';
COMMENT ON COLUMN pl_vtrust.SPLIT_FLAG  IS '是否允许拆分标记 1是 0否';

ALTER TABLE pl_vtrust ADD pl_drwrAcctName VARCHAR2(300);
COMMENT ON COLUMN pl_vtrust.pl_drwrAcctName  IS '出票人账户名称';

ALTER TABLE pl_vtrust ADD pl_pyeeAcctName VARCHAR2(300);
COMMENT ON COLUMN pl_vtrust.pl_pyeeAcctName  IS '收票人账户名称';

ALTER TABLE pl_vtrust ADD pl_accptrAcctName VARCHAR2(300);
COMMENT ON COLUMN pl_vtrust.pl_accptrAcctName  IS '承兑人账户名称';

--贴现表

ALTER TABLE PL_DISCOUNT ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PL_DISCOUNT.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE PL_DISCOUNT ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PL_DISCOUNT.END_RANGE_NO  IS '票据结束子区间号';

ALTER TABLE PL_DISCOUNT ADD STANDARD_AMT NUMBER(20,2)  DEFAULT 0.01;
COMMENT ON COLUMN PL_DISCOUNT.STANDARD_AMT  IS '标准金额';

ALTER TABLE PL_DISCOUNT ADD TRADE_AMT NUMBER(20,2)  DEFAULT 0;
COMMENT ON COLUMN PL_DISCOUNT.TRADE_AMT  IS '交易金额(等分化票据实际交易金额)';

ALTER TABLE PL_DISCOUNT ADD DRAFT_SOURCE VARCHAR2(6)  DEFAULT 'CS01';
COMMENT ON COLUMN PL_DISCOUNT.DRAFT_SOURCE  IS '票据来源';

ALTER TABLE PL_DISCOUNT ADD SPLIT_FLAG VARCHAR2(1)  DEFAULT '0';
COMMENT ON COLUMN PL_DISCOUNT.SPLIT_FLAG  IS '是否允许拆分标记 1是 0否';

ALTER TABLE PL_DISCOUNT ADD HILR_ID VARCHAR2(40);
COMMENT ON COLUMN PL_DISCOUNT.HILR_ID  IS '持有id';

ALTER TABLE PL_DISCOUNT ADD SPLIT_ID VARCHAR2(40);
COMMENT ON COLUMN PL_DISCOUNT.SPLIT_ID  IS '拆分前的大票主键id';

ALTER TABLE PL_DISCOUNT ADD TRANS_ID VARCHAR2(40);
COMMENT ON COLUMN PL_DISCOUNT.TRANS_ID  IS '交易ID';

--保贴表

ALTER TABLE PED_GUARANTEE_CREDIT ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PED_GUARANTEE_CREDIT.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE PED_GUARANTEE_CREDIT ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PED_GUARANTEE_CREDIT.END_RANGE_NO  IS '票据结束子区间号';

--在银承明细表

ALTER TABLE PL_ONLINE_ACPT_DETAIL ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PL_ONLINE_ACPT_DETAIL.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE PL_ONLINE_ACPT_DETAIL ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PL_ONLINE_ACPT_DETAIL.END_RANGE_NO  IS '票据结束子区间号';

ALTER TABLE PL_ONLINE_ACPT_DETAIL ADD STANDARD_AMT NUMBER(20,2)  DEFAULT 0.01;
COMMENT ON COLUMN PL_ONLINE_ACPT_DETAIL.STANDARD_AMT  IS '标准金额';

ALTER TABLE PL_ONLINE_ACPT_DETAIL ADD TRADE_AMT NUMBER(20,2)  DEFAULT 0;
COMMENT ON COLUMN PL_ONLINE_ACPT_DETAIL.TRADE_AMT  IS '交易金额(等分化票据实际交易金额)';

ALTER TABLE PL_ONLINE_ACPT_DETAIL ADD DRAFT_SOURCE VARCHAR2(6)  DEFAULT 'CS01';
COMMENT ON COLUMN PL_ONLINE_ACPT_DETAIL.DRAFT_SOURCE  IS '票据来源';

ALTER TABLE PL_ONLINE_ACPT_DETAIL ADD SPLIT_FLAG VARCHAR2(1)  DEFAULT '0';
COMMENT ON COLUMN PL_ONLINE_ACPT_DETAIL.SPLIT_FLAG  IS '是否允许拆分标记 1是 0否';

ALTER TABLE PL_ONLINE_ACPT_DETAIL ADD TRANS_ID VARCHAR2(40);
COMMENT ON COLUMN PL_ONLINE_ACPT_DETAIL.TRANS_ID  IS '签收交易ID';

ALTER TABLE PL_ONLINE_ACPT_DETAIL ADD SEND_TRANS_ID VARCHAR2(40);
COMMENT ON COLUMN PL_ONLINE_ACPT_DETAIL.SEND_TRANS_ID  IS '申请交易ID';

ALTER TABLE PL_ONLINE_ACPT_DETAIL ADD HILR_ID VARCHAR2(40);
COMMENT ON COLUMN PL_ONLINE_ACPT_DETAIL.HILR_ID  IS '持有id';

ALTER TABLE PL_ONLINE_ACPT_DETAIL ADD ISSUER_ACCT_NAME VARCHAR2(320);
COMMENT ON COLUMN PL_ONLINE_ACPT_DETAIL.ISSUER_ACCT_NAME  IS '出票人账号名称';

ALTER TABLE PL_ONLINE_ACPT_DETAIL ADD PAYEE_ACCT_NAME VARCHAR2(320);
COMMENT ON COLUMN PL_ONLINE_ACPT_DETAIL.PAYEE_ACCT_NAME  IS '收票人账号名称';

--在线银承批次表
ALTER TABLE PL_ONLINE_ACPT_BATCH ADD ORI_CONTRACT_AMT NUMBER(20,2);
COMMENT ON COLUMN PL_ONLINE_ACPT_BATCH.ORI_CONTRACT_AMT  IS '原合同金额';



--背书表

ALTER TABLE cd_endorsementLog ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN cd_endorsementLog.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE cd_endorsementLog ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN cd_endorsementLog.END_RANGE_NO  IS '票据结束子区间号';

ALTER TABLE cd_endorsementLog ADD DRAFT_SOURCE VARCHAR2(6);
COMMENT ON COLUMN cd_endorsementLog.DRAFT_SOURCE  IS '票据来源';


--托收表

ALTER TABLE BT_COLLECTION_SEND ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN BT_COLLECTION_SEND.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE BT_COLLECTION_SEND ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN BT_COLLECTION_SEND.END_RANGE_NO  IS '票据结束子区间号';

ALTER TABLE BT_COLLECTION_SEND ADD STANDARD_AMT NUMBER(20,2)  DEFAULT 0.01;
COMMENT ON COLUMN BT_COLLECTION_SEND.STANDARD_AMT  IS '标准金额';

ALTER TABLE BT_COLLECTION_SEND ADD TRADE_AMT NUMBER(20,2)  DEFAULT 0;
COMMENT ON COLUMN BT_COLLECTION_SEND.TRADE_AMT  IS '交易金额(等分化票据实际交易金额)';

ALTER TABLE BT_COLLECTION_SEND ADD DRAFT_SOURCE VARCHAR2(6)  DEFAULT 'CS01';
COMMENT ON COLUMN BT_COLLECTION_SEND.DRAFT_SOURCE  IS '票据来源';

ALTER TABLE BT_COLLECTION_SEND ADD SPLIT_FLAG VARCHAR2(1)  DEFAULT '0';
COMMENT ON COLUMN BT_COLLECTION_SEND.SPLIT_FLAG  IS '是否允许拆分标记 1是 0否';

ALTER TABLE BT_COLLECTION_SEND ADD HILR_ID VARCHAR2(40);
COMMENT ON COLUMN BT_COLLECTION_SEND.HILR_ID  IS '持有id';

ALTER TABLE BT_COLLECTION_SEND ADD TRANS_ID VARCHAR2(40);
COMMENT ON COLUMN BT_COLLECTION_SEND.TRANS_ID  IS '交易ID';

ALTER TABLE BT_COLLECTION_SEND ADD IS_PURSUE VARCHAR2(10);
COMMENT ON COLUMN BT_COLLECTION_SEND.IS_PURSUE  IS '是否追索';


--账务管家表

ALTER TABLE DRAFT_ACCOUNT_MANAGEMENT ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN DRAFT_ACCOUNT_MANAGEMENT.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE DRAFT_ACCOUNT_MANAGEMENT ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN DRAFT_ACCOUNT_MANAGEMENT.END_RANGE_NO  IS '票据结束子区间号';

ALTER TABLE DRAFT_ACCOUNT_MANAGEMENT ADD STANDARD_AMT NUMBER(20,2)  DEFAULT 0.01;
COMMENT ON COLUMN DRAFT_ACCOUNT_MANAGEMENT.STANDARD_AMT  IS '标准金额';

ALTER TABLE DRAFT_ACCOUNT_MANAGEMENT ADD TRADE_AMT NUMBER(20,2)  DEFAULT 0;
COMMENT ON COLUMN DRAFT_ACCOUNT_MANAGEMENT.TRADE_AMT  IS '交易金额(等分化票据实际交易金额)';

ALTER TABLE DRAFT_ACCOUNT_MANAGEMENT ADD DRAFT_SOURCE VARCHAR2(6)  DEFAULT 'CS01';
COMMENT ON COLUMN DRAFT_ACCOUNT_MANAGEMENT.DRAFT_SOURCE  IS '票据来源';

ALTER TABLE DRAFT_ACCOUNT_MANAGEMENT ADD SPLIT_FLAG VARCHAR2(1)  DEFAULT '0';
COMMENT ON COLUMN DRAFT_ACCOUNT_MANAGEMENT.SPLIT_FLAG  IS '是否允许拆分标记 1是 0否';

ALTER TABLE DRAFT_ACCOUNT_MANAGEMENT ADD pl_drwrAcctName VARCHAR2(300);
COMMENT ON COLUMN DRAFT_ACCOUNT_MANAGEMENT.pl_drwrAcctName  IS '出票人账户名称';

ALTER TABLE DRAFT_ACCOUNT_MANAGEMENT ADD pl_pyeeAcctName VARCHAR2(300);
COMMENT ON COLUMN DRAFT_ACCOUNT_MANAGEMENT.pl_pyeeAcctName  IS '收票人账户名称';

ALTER TABLE DRAFT_ACCOUNT_MANAGEMENT ADD pl_accptrAcctName VARCHAR2(300);
COMMENT ON COLUMN DRAFT_ACCOUNT_MANAGEMENT.pl_accptrAcctName  IS '承兑人账户名称';

ALTER TABLE DRAFT_ACCOUNT_MANAGEMENT ADD BILL_ID VARCHAR2(20);
COMMENT ON COLUMN DRAFT_ACCOUNT_MANAGEMENT.BILL_ID  IS '票据id';

--mis抽数表

ALTER TABLE MIS_EDRAFT ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN MIS_EDRAFT.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE MIS_EDRAFT ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN MIS_EDRAFT.END_RANGE_NO  IS '票据结束子区间号';

ALTER TABLE MIS_EDRAFT ADD STANDARD_AMT NUMBER(20,2)  DEFAULT 0.01;
COMMENT ON COLUMN MIS_EDRAFT.STANDARD_AMT  IS '标准金额';

ALTER TABLE MIS_EDRAFT ADD TRADE_AMT NUMBER(20,2)  DEFAULT 0;
COMMENT ON COLUMN MIS_EDRAFT.TRADE_AMT  IS '交易金额(等分化票据实际交易金额)';

ALTER TABLE MIS_EDRAFT ADD DRAFT_SOURCE VARCHAR2(6)  DEFAULT 'CS01';
COMMENT ON COLUMN MIS_EDRAFT.DRAFT_SOURCE  IS '票据来源';

ALTER TABLE MIS_EDRAFT ADD SPLIT_FLAG VARCHAR2(1)  DEFAULT '0';
COMMENT ON COLUMN MIS_EDRAFT.SPLIT_FLAG  IS '是否允许拆分标记 1是 0否';


--网银对账票据明细

ALTER TABLE PED_CHECK_LIST ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PED_CHECK_LIST.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE PED_CHECK_LIST ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PED_CHECK_LIST.END_RANGE_NO  IS '票据结束子区间号';


--每日资产表

ALTER TABLE PED_ASSET_DAILY ADD BEGIN_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PED_ASSET_DAILY.BEGIN_RANGE_NO  IS '票据开始子区间号';

ALTER TABLE PED_ASSET_DAILY ADD END_RANGE_NO VARCHAR2(12) DEFAULT '0';
COMMENT ON COLUMN PED_ASSET_DAILY.END_RANGE_NO  IS '票据结束子区间号';

ALTER TABLE PED_ASSET_DAILY ADD DRAFT_SOURCE VARCHAR2(6)  DEFAULT 'CS01';
COMMENT ON COLUMN PED_ASSET_DAILY.DRAFT_SOURCE  IS '票据来源';

ALTER TABLE PED_ASSET_DAILY ADD SPLIT_FLAG VARCHAR2(1)  DEFAULT '0';
COMMENT ON COLUMN PED_ASSET_DAILY.SPLIT_FLAG  IS '是否允许拆分标记 1是 0否';

ALTER TABLE PED_ASSET_DAILY ADD pl_pyeeAcctName VARCHAR2(300);
COMMENT ON COLUMN PED_ASSET_DAILY.pl_pyeeAcctName  IS '收款人账户名称';

ALTER TABLE PED_ASSET_DAILY ADD pl_accptrAcctName VARCHAR2(300);
COMMENT ON COLUMN PED_ASSET_DAILY.pl_accptrAcctName  IS '承兑人账号名称';

ALTER TABLE PED_ASSET_DAILY ADD pl_SIssuerAcctName VARCHAR2(300);
COMMENT ON COLUMN PED_ASSET_DAILY.pl_SIssuerAcctName  IS '出票人账号名称';

ALTER TABLE PED_ASSET_DAILY ADD pl_accptrAcctNO VARCHAR2(300);
COMMENT ON COLUMN PED_ASSET_DAILY.pl_accptrAcctNO  IS '承兑人账号';

ALTER TABLE PED_ASSET_DAILY ADD pl_accptr VARCHAR2(300);
COMMENT ON COLUMN PED_ASSET_DAILY.pl_accptr  IS '承兑人名称';



--机构
ALTER TABLE t_department ADD TX_FLAG VARCHAR2(50);
COMMENT ON COLUMN t_department.TX_FLAG  IS '在线贴现开关';

ALTER TABLE t_department ADD TX_ID VARCHAR2(50);
COMMENT ON COLUMN t_department.TX_ID  IS '中台贴现机构ID';

ALTER TABLE PED_ONLINE_ACPT_INFO ADD PAYEE_CUST_NAME VARCHAR2(240);
COMMENT ON COLUMN PED_ONLINE_ACPT_INFO.PAYEE_CUST_NAME  IS '收票人客户名称';

ALTER TABLE PED_ONLINE_ACPT_INFO_HIST ADD PAYEE_CUST_NAME VARCHAR2(240);
COMMENT ON COLUMN PED_ONLINE_ACPT_INFO_HIST.PAYEE_CUST_NAME  IS '收票人客户名称';

------出池后续处理票据批次信息表
ALTER TABLE PL_BATCH_INFO ADD DISCOUNT_RATE_MODE VARCHAR2(10);
COMMENT ON COLUMN PL_BATCH_INFO.DISCOUNT_RATE_MODE  IS '贴现利息方式';

ALTER TABLE PL_BATCH_INFO ADD THIRD_PAY_RATE VARCHAR2(10);
COMMENT ON COLUMN PL_BATCH_INFO.THIRD_PAY_RATE  IS '第三方支付比例';

ALTER TABLE PL_BATCH_INFO ADD RATE_AMT NUMBER(20,2);
COMMENT ON COLUMN PL_BATCH_INFO.RATE_AMT  IS '实付利息金额';

----------------对账
ALTER TABLE PED_CHECK_BATCH ADD pledge_No VARCHAR2(50);
COMMENT ON COLUMN PED_CHECK_BATCH.pledge_No  IS '质押清单编号';
ALTER TABLE PED_CHECK ADD pledge_No VARCHAR2(50);
COMMENT ON COLUMN PED_CHECK.pledge_No  IS '质押清单编号';
ALTER TABLE PED_CHECK_LIST ADD pledge_No VARCHAR2(50);
COMMENT ON COLUMN PED_CHECK_LIST.pledge_No  IS '质押清单编号';

alter table PED_ASSET_REGISTER_HIS modify ASSET_NO varchar2(60);

alter table PED_ASSET_REGISTER modify ASSET_NO varchar2(60);

alter table PED_ASSET_REGISTER_CACHE modify ASSET_NO varchar2(60);

alter table PED_ONLINE_HANDLE_LOG modify BILL_NO varchar2(160);

alter table PED_PROTOCOL modify CREDIT_FREE_AMOUNT NUMBER(20,2);
alter table PED_PROTOCOL modify CREDIT_USED_AMOUNT NUMBER(20,2);

alter table trans_log modify m_txcode varchar2(12);

--报表相关表扩充字段
alter table R_POOL_REPORT_INFO modify PRO_COMP_YEST_NUM     NUMBER(20,2);
alter table R_POOL_REPORT_INFO modify PRO_COMP_YEST_RATIO   NUMBER(20,4);
alter table R_POOL_REPORT_INFO modify PRO_COMP_LAST_M_NUM   NUMBER(20,2);
alter table R_POOL_REPORT_INFO modify PRO_COMP_LAST_M_RATIO NUMBER(20,4);
alter table R_POOL_REPORT_INFO modify PRO_COMP_LAST_Y_NUM   NUMBER(20,2);
alter table R_POOL_REPORT_INFO modify PRO_COMP_LAST_Y_RATIO NUMBER(20,4);
alter table R_POOL_REPORT_INFO modify DRAFT_TOTAL_AMT       NUMBER(20,2);
alter table R_POOL_REPORT_INFO modify DRAFT_COMP_YEST_NUM    NUMBER(20,2);
alter table R_POOL_REPORT_INFO modify DRAFT_COMP_YEST_RATIO  NUMBER(20,4);
alter table R_POOL_REPORT_INFO modify DRAFT_COMP_LAST_M_NUM  NUMBER(20,2);
alter table R_POOL_REPORT_INFO modify DRAFT_COMP_LAST_M_RATIO NUMBER(20,4);
alter table R_POOL_REPORT_INFO modify DRAFT_COMP_LAST_Y_NUM  NUMBER(20,2);
alter table R_POOL_REPORT_INFO modify DRAFT_COMP_LAST_Y_RATIO NUMBER(20,4);
alter table R_POOL_REPORT_INFO modify MARGIN_TOTAL_AMT       NUMBER(20,2);
alter table R_POOL_REPORT_INFO modify MARGIN_COMP_YEST_NUM     NUMBER(20,2);
alter table R_POOL_REPORT_INFO modify MARGIN_COMP_YEST_RATIO   NUMBER(20,4);
alter table R_POOL_REPORT_INFO modify MARGIN_COMP_LAST_M_NUM   NUMBER(20,2);
alter table R_POOL_REPORT_INFO modify MARGIN_COMP_LAST_M_RATIO NUMBER(20,4);
alter table R_POOL_REPORT_INFO modify MARGIN_COMP_LAST_Y_NUM   NUMBER(20,2);
alter table R_POOL_REPORT_INFO modify MARGIN_COMP_LAST_Y_RATIO NUMBER(20,4);



alter table R_CREDIT_REPORT_INFO modify YEST_NUM     NUMBER(20,2);
alter table R_CREDIT_REPORT_INFO modify YEST_RATIO   NUMBER(20,4);
alter table R_CREDIT_REPORT_INFO modify LAST_M_NUM   NUMBER(20,2);
alter table R_CREDIT_REPORT_INFO modify LAST_M_RATIO NUMBER(20,4);
alter table R_CREDIT_REPORT_INFO modify LAST_Y_NUM   NUMBER(20,2);
alter table R_CREDIT_REPORT_INFO modify LAST_Y_RATIO NUMBER(20,4);


