--客户信息移植
INSERT INTO BO_CUSTOMER_REGISTER (
SELECT P_POOLINFOID,P_CUSTNUMBER,P_CUSTNAME,'PJC033',P_EFFSTARTDATE,TO_DATE('20211029','YYYYMMDD'),TO_DATE('20211029','YYYYMMDD'),'0','0' FROM PED_PROTOCOL
 );
 
--资产登记表移植 

UPDATE PED_BAIL_DETAIL t SET  t.BD_CRDT_USED = 0 ,t.BD_CRDT_FREE = t.BD_CRDT_TOTAL;
INSERT INTO PED_ASSET_REGISTER (
SELECT  t.BD_ID,'YZ',t.AT_ID,'YZ','03','YZ',t.POOL_AGREEMENT,t.ACCT_NO,'ED_21','FX_01',t.BD_CRDT_TOTAL, TO_DATE('20211029','YYYYMMDD'),
TO_DATE('20211029','YYYYMMDD'),TO_DATE('20211029','YYYYMMDD'),TO_DATE('20211029','YYYYMMDD'),TO_DATE('20211029','YYYYMMDD'),'N' FROM PED_BAIL_DETAIL t
); 
 
INSERT INTO PED_ASSET_REGISTER (
SELECT t.ID,'YZ',t.AT_ID,'票据池('||t.CUST_NAME||')','03',t.CUST_NO,t.POOL_AGREEMENT,t.PL_DRAFTNB,'ED_10',t.RICK_LEVEL,t.PL_ISSEAMT,
t.PL_DUEDT,t.PL_DUEDT,TO_DATE('20211029','YYYYMMDD'),TO_DATE('20211029','YYYYMMDD'),TO_DATE('20211029','YYYYMMDD'),'N' 
FROM PL_POOL t WHERE t.PL_STATUS IN ('DS_02','DS_06') AND T.RICK_LEVEL IN ('FX_01','FX_02')
);

--移植ap_id  cust_pool_name  cert_code 
UPDATE PED_ASSET_REGISTER a SET a.AP_ID =  (
SELECT b.ap FROM ( SELECT t.ID id, p.AP_ID ap FROM PED_ASSET_REGISTER T LEFT JOIN PED_ASSET_POOL P ON T.BPS_NO = P.BPS_NO ) b WHERE a.ID = b.id );
UPDATE PED_ASSET_REGISTER a SET a.CUST_POOL_NAME =  (
SELECT b.name FROM ( SELECT t.ID id,'票据池('||p.CUST_NAME||')' name FROM PED_ASSET_REGISTER T LEFT JOIN PED_ASSET_POOL P ON T.BPS_NO = P.BPS_NO ) b WHERE a.ID = b.id );
UPDATE PED_ASSET_REGISTER a SET a.CERT_CODE =  (
SELECT b.cust FROM ( SELECT t.ID id,p.CUST_NO cust FROM PED_ASSET_REGISTER T LEFT JOIN PED_ASSET_POOL P ON T.BPS_NO = P.BPS_NO ) b WHERE a.ID = b.id );

--融资业务登记表
INSERT INTO PED_CREDIT_REGISTER (
SELECT t.CREDIT_DETAIL_ID,'YZ',t.BPS_NO,t.CREDIT_DETAIL_ID,t.LOAN_NO,'1',t.CRDT_NO,'0',t.LOAN_TYPE,t.RISK_LEVEL,
t.LOAN_AMOUNT,1,t.ACTUAL_AMOUNT,t.ACTUAL_AMOUNT,t.EDN_TIME,t.TRANS_TIME,TO_DATE('20211029','YYYYMMDD'),TO_DATE('20211029','YYYYMMDD')
FROM PED_CREDIT_DETAIL t  WHERE t.LOAN_STATUS ='JJ_01'
);
--移植apId
UPDATE PED_CREDIT_REGISTER a SET a.AP_ID =  (
SELECT b.ap FROM ( SELECT t.ID id, p.AP_ID ap FROM PED_CREDIT_REGISTER T LEFT JOIN PED_ASSET_POOL P ON T.BPS_NO = P.BPS_NO ) b WHERE a.ID = b.id );